### ISSUE TITLE
notificationReceived and flag launchedWithNotification not working

### ISSUE THREAD

**Issue by aerlijman** [Wizcorp/phonegap-plugin-localNotifications#4]
In the notificationReceived event there are 3 possible options: launchWithNotification, launch when the app is active and the other. The thing is that only the second and the third are working. I never get the first one to work, so I can not make a difference between when I click  it in the notification center or when I get it. Ideas?

**Comment by aogilvie** [comment]
Sorry, just to be clear.. Do you mean difference between tap in the notification center (top of the screen) or tapping on the application icon? If yes, I do not believe it is possible with our plugin to do this.

**Comment by aerlijman** [comment]
So.. how do you reach that part of the code you have that I can not reach as explained in my first post? I think I am missing something because the variable flag you have called launchedWithNotification is always NO.
Ideas?

**Comment by wcwynn** [comment]
The description of this issue is a bit vague but I suspect the 3 possible cases you are referring to is the code located here: https://github.com/Wizcorp/phonegap-plugin-localNotifications/blob/v2.3/ios/project/Plugins/LocalNotification/LocalNotification.m#L198

Here is how you can trigger these 3 cases using the test app:

Launch the test app.
1. Add Notification and wait for the notification to fire.
2. Add Notification, put the app in the background.  When the notification fires, click the notification.
3. Add Notification, put the app in the background, double-click the home button and then kill the app (by long-pressing the app icon at the bottom of the screen and then clicking the red 'minus' symbol).  When the notification fires, click the notification.

Note that for case 3 you won't be able to verify it in the debugger as you're required to kill the app, but that doesn't mean the code is not working.

All 3 cases are tested and working.  If you find otherwise, please re-open this issue.
